// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using serviceoncologie.Data;

#nullable disable

namespace serviceoncologie.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250316155717_deleteconomn")]
    partial class deleteconomn
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("serviceoncologie.Data.Models.CommissionStaf", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DateCommission")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("CommissionStaffs");
                });

            modelBuilder.Entity("serviceoncologie.Data.Models.CommissionStafMedecin", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CommissionStafId")
                        .HasColumnType("int");

                    b.Property<int>("MedecinId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CommissionStafId");

                    b.HasIndex("MedecinId");

                    b.ToTable("CommissionStafMedecins");
                });

            modelBuilder.Entity("serviceoncologie.Data.Models.Consultation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DateConsultation")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("MedecinId")
                        .HasColumnType("int");

                    b.Property<string>("Observation")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("PatientId")
                        .HasColumnType("int");

                    b.Property<double>("Poids")
                        .HasColumnType("double");

                    b.Property<double>("Taille")
                        .HasColumnType("double");

                    b.Property<double>("Temperature")
                        .HasColumnType("double");

                    b.Property<double>("Tension")
                        .HasColumnType("double");

                    b.HasKey("Id");

                    b.HasIndex("MedecinId");

                    b.HasIndex("PatientId");

                    b.ToTable("Consultations");
                });

            modelBuilder.Entity("serviceoncologie.Data.Models.ConsultationMaladie", b =>
                {
                    b.Property<int>("ConsultationId")
                        .HasColumnType("int")
                        .HasColumnOrder(1);

                    b.Property<int>("MaladieId")
                        .HasColumnType("int")
                        .HasColumnOrder(2);

                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.HasKey("ConsultationId", "MaladieId");

                    b.HasIndex("MaladieId");

                    b.ToTable("ConsultationMaladies");
                });

            modelBuilder.Entity("serviceoncologie.Data.Models.DemandeRdv", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DateDeDemande")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("PatientId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PatientId");

                    b.ToTable("DemandesRdv");
                });

            modelBuilder.Entity("serviceoncologie.Data.Models.Maladie", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("ConsultationId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("MedecinId")
                        .HasColumnType("int");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("codecim")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("ConsultationId");

                    b.HasIndex("MedecinId");

                    b.ToTable("Maladies");
                });

            modelBuilder.Entity("serviceoncologie.Data.Models.Paiement", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DatePaiement")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("MethodePaiement")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<double>("Montant")
                        .HasColumnType("double");

                    b.Property<int>("PatientId")
                        .HasColumnType("int");

                    b.Property<int>("RdvId")
                        .HasColumnType("int");

                    b.Property<string>("Statut")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("PatientId");

                    b.HasIndex("RdvId")
                        .IsUnique();

                    b.ToTable("Paiements");
                });

            modelBuilder.Entity("serviceoncologie.Data.Models.Patient", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Adresse")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Categorie")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("DateNaissance")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("NCIN")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("varchar(8)");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("NumeroTelephone")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("varchar(8)");

                    b.Property<double>("Poids")
                        .HasColumnType("double");

                    b.Property<string>("Prenom")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("SituationSocial")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("SousCategorie")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<double>("Taille")
                        .HasColumnType("double");

                    b.HasKey("Id");

                    b.ToTable("Patients");
                });

            modelBuilder.Entity("serviceoncologie.Data.Models.Rdv", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DateRdv")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("DemandeRdvId")
                        .HasColumnType("int");

                    b.Property<int?>("DemandeRdvId1")
                        .HasColumnType("int");

                    b.Property<string>("Etat")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("MedecinId")
                        .HasColumnType("int");

                    b.Property<string>("Observation")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("PatientId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DemandeRdvId")
                        .IsUnique();

                    b.HasIndex("DemandeRdvId1")
                        .IsUnique();

                    b.HasIndex("MedecinId");

                    b.HasIndex("PatientId");

                    b.ToTable("Rdvs");
                });

            modelBuilder.Entity("serviceoncologie.Data.Models.Tache", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Libelle")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Taches");
                });

            modelBuilder.Entity("serviceoncologie.Data.Models.TacheUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("DateAdded")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("TacheId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TacheId");

                    b.HasIndex("UserId");

                    b.ToTable("TacheUsers");
                });

            modelBuilder.Entity("serviceoncologie.Data.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Adresse")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int?>("CommissionStafId")
                        .HasColumnType("int");

                    b.Property<DateTime>("DateDeNaissance")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("NCIN")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("varchar(8)");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Prenom")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Sexe")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("SituationSocial")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Telephone")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("CommissionStafId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("serviceoncologie.Data.Models.CommissionStafMedecin", b =>
                {
                    b.HasOne("serviceoncologie.Data.Models.CommissionStaf", "CommissionStaf")
                        .WithMany("CommissionStafMedecins")
                        .HasForeignKey("CommissionStafId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("serviceoncologie.Data.Models.User", "Medecin")
                        .WithMany("CommissionStafMedecins")
                        .HasForeignKey("MedecinId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CommissionStaf");

                    b.Navigation("Medecin");
                });

            modelBuilder.Entity("serviceoncologie.Data.Models.Consultation", b =>
                {
                    b.HasOne("serviceoncologie.Data.Models.User", "Medecin")
                        .WithMany()
                        .HasForeignKey("MedecinId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("serviceoncologie.Data.Models.Patient", "Patient")
                        .WithMany()
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Medecin");

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("serviceoncologie.Data.Models.ConsultationMaladie", b =>
                {
                    b.HasOne("serviceoncologie.Data.Models.Consultation", "Consultation")
                        .WithMany("ConsultationMaladies")
                        .HasForeignKey("ConsultationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("serviceoncologie.Data.Models.Maladie", "Maladie")
                        .WithMany("ConsultationMaladies")
                        .HasForeignKey("MaladieId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Consultation");

                    b.Navigation("Maladie");
                });

            modelBuilder.Entity("serviceoncologie.Data.Models.DemandeRdv", b =>
                {
                    b.HasOne("serviceoncologie.Data.Models.Patient", "Patient")
                        .WithMany("DemandesRdv")
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("serviceoncologie.Data.Models.Maladie", b =>
                {
                    b.HasOne("serviceoncologie.Data.Models.Consultation", null)
                        .WithMany("Maladies")
                        .HasForeignKey("ConsultationId");

                    b.HasOne("serviceoncologie.Data.Models.User", "Medecin")
                        .WithMany("MaladiesCodées")
                        .HasForeignKey("MedecinId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Medecin");
                });

            modelBuilder.Entity("serviceoncologie.Data.Models.Paiement", b =>
                {
                    b.HasOne("serviceoncologie.Data.Models.Patient", "Patient")
                        .WithMany("Paiements")
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("serviceoncologie.Data.Models.Rdv", "Rdv")
                        .WithOne("Paiement")
                        .HasForeignKey("serviceoncologie.Data.Models.Paiement", "RdvId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Patient");

                    b.Navigation("Rdv");
                });

            modelBuilder.Entity("serviceoncologie.Data.Models.Rdv", b =>
                {
                    b.HasOne("serviceoncologie.Data.Models.DemandeRdv", "DemandeRdv")
                        .WithOne()
                        .HasForeignKey("serviceoncologie.Data.Models.Rdv", "DemandeRdvId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("serviceoncologie.Data.Models.DemandeRdv", null)
                        .WithOne("Rdv")
                        .HasForeignKey("serviceoncologie.Data.Models.Rdv", "DemandeRdvId1");

                    b.HasOne("serviceoncologie.Data.Models.User", "Medecin")
                        .WithMany()
                        .HasForeignKey("MedecinId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("serviceoncologie.Data.Models.Patient", "Patient")
                        .WithMany("Rdvs")
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DemandeRdv");

                    b.Navigation("Medecin");

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("serviceoncologie.Data.Models.TacheUser", b =>
                {
                    b.HasOne("serviceoncologie.Data.Models.Tache", "Tache")
                        .WithMany("TacheUsers")
                        .HasForeignKey("TacheId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("serviceoncologie.Data.Models.User", "User")
                        .WithMany("TacheUsers")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tache");

                    b.Navigation("User");
                });

            modelBuilder.Entity("serviceoncologie.Data.Models.User", b =>
                {
                    b.HasOne("serviceoncologie.Data.Models.CommissionStaf", null)
                        .WithMany("Medecins")
                        .HasForeignKey("CommissionStafId");
                });

            modelBuilder.Entity("serviceoncologie.Data.Models.CommissionStaf", b =>
                {
                    b.Navigation("CommissionStafMedecins");

                    b.Navigation("Medecins");
                });

            modelBuilder.Entity("serviceoncologie.Data.Models.Consultation", b =>
                {
                    b.Navigation("ConsultationMaladies");

                    b.Navigation("Maladies");
                });

            modelBuilder.Entity("serviceoncologie.Data.Models.DemandeRdv", b =>
                {
                    b.Navigation("Rdv");
                });

            modelBuilder.Entity("serviceoncologie.Data.Models.Maladie", b =>
                {
                    b.Navigation("ConsultationMaladies");
                });

            modelBuilder.Entity("serviceoncologie.Data.Models.Patient", b =>
                {
                    b.Navigation("DemandesRdv");

                    b.Navigation("Paiements");

                    b.Navigation("Rdvs");
                });

            modelBuilder.Entity("serviceoncologie.Data.Models.Rdv", b =>
                {
                    b.Navigation("Paiement");
                });

            modelBuilder.Entity("serviceoncologie.Data.Models.Tache", b =>
                {
                    b.Navigation("TacheUsers");
                });

            modelBuilder.Entity("serviceoncologie.Data.Models.User", b =>
                {
                    b.Navigation("CommissionStafMedecins");

                    b.Navigation("MaladiesCodées");

                    b.Navigation("TacheUsers");
                });
#pragma warning restore 612, 618
        }
    }
}
