// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using serviceoncologie.Data;

#nullable disable

namespace serviceoncologie.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250401185618_addphotoprofil")]
    partial class addphotoprofil
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("Admission", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ConsultationId")
                        .HasColumnType("int");

                    b.Property<DateTime>("DateAdmission")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("DateSortie")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("DecisionStafId")
                        .HasColumnType("int");

                    b.Property<string>("MotifAdmission")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("MotifSortie")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ConsultationId");

                    b.HasIndex("DecisionStafId");

                    b.ToTable("Admissions");
                });

            modelBuilder.Entity("StafMedecin", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("commissionstafid")
                        .HasColumnType("int");

                    b.Property<int>("userid")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("commissionstafid");

                    b.HasIndex("userid");

                    b.ToTable("StafMedecins");
                });

            modelBuilder.Entity("serviceoncologie.Data.Models.CommissionStaf", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DateCreation")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("CommissionStafs");
                });

            modelBuilder.Entity("serviceoncologie.Data.Models.Consultation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DateConsultation")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("DossierId")
                        .HasColumnType("int");

                    b.Property<int>("MedecinId")
                        .HasColumnType("int");

                    b.Property<string>("Observation")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("PatientId")
                        .HasColumnType("int");

                    b.Property<double>("Poids")
                        .HasColumnType("double");

                    b.Property<double>("Taille")
                        .HasColumnType("double");

                    b.Property<double>("Temperature")
                        .HasColumnType("double");

                    b.Property<double>("Tension")
                        .HasColumnType("double");

                    b.HasKey("Id");

                    b.HasIndex("DossierId");

                    b.HasIndex("MedecinId");

                    b.HasIndex("PatientId");

                    b.ToTable("Consultations");
                });

            modelBuilder.Entity("serviceoncologie.Data.Models.ConsultationMaladie", b =>
                {
                    b.Property<int>("ConsultationId")
                        .HasColumnType("int")
                        .HasColumnOrder(1);

                    b.Property<int>("MaladieId")
                        .HasColumnType("int")
                        .HasColumnOrder(2);

                    b.Property<int>("DossierId")
                        .HasColumnType("int");

                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.HasKey("ConsultationId", "MaladieId");

                    b.HasIndex("DossierId");

                    b.HasIndex("MaladieId");

                    b.ToTable("ConsultationMaladies");
                });

            modelBuilder.Entity("serviceoncologie.Data.Models.ConsultationPrestation", b =>
                {
                    b.Property<int>("ConsultationId")
                        .HasColumnType("int");

                    b.Property<int>("PrestationMedicaleId")
                        .HasColumnType("int");

                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.HasKey("ConsultationId", "PrestationMedicaleId");

                    b.HasIndex("PrestationMedicaleId");

                    b.ToTable("ConsultationPrestations");
                });

            modelBuilder.Entity("serviceoncologie.Data.Models.Cure", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DateCure")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("MedicamentId")
                        .HasColumnType("int");

                    b.Property<string>("Observation")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("ProtocoleId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("MedicamentId");

                    b.HasIndex("ProtocoleId");

                    b.ToTable("Cures");
                });

            modelBuilder.Entity("serviceoncologie.Data.Models.Dci", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Libelle")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Dcis");
                });

            modelBuilder.Entity("serviceoncologie.Data.Models.DciMedicament", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("DciId")
                        .HasColumnType("int");

                    b.Property<int>("MedicamentId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DciId");

                    b.HasIndex("MedicamentId");

                    b.ToTable("DciMedicaments");
                });

            modelBuilder.Entity("serviceoncologie.Data.Models.DecisionStaf", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CommissionStafId")
                        .HasColumnType("int");

                    b.Property<int>("ConsultationId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("DossierId")
                        .HasColumnType("int");

                    b.Property<string>("Observation")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CommissionStafId");

                    b.HasIndex("ConsultationId");

                    b.HasIndex("DossierId");

                    b.ToTable("DecisionStafs");
                });

            modelBuilder.Entity("serviceoncologie.Data.Models.DemandeRdv", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DateDeDemande")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("PatientId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PatientId");

                    b.ToTable("DemandesRdv");
                });

            modelBuilder.Entity("serviceoncologie.Data.Models.Dossier", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DateCreation")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("NumeroDossier")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Dossiers");
                });

            modelBuilder.Entity("serviceoncologie.Data.Models.Maladie", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("ConsultationId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("MedecinId")
                        .HasColumnType("int");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("codecim")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("ConsultationId");

                    b.HasIndex("MedecinId");

                    b.ToTable("Maladies");
                });

            modelBuilder.Entity("serviceoncologie.Data.Models.Medicament", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("LibelleMedicament")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("LibelleMedicament");

                    b.HasKey("Id");

                    b.ToTable("Medicaments");
                });

            modelBuilder.Entity("serviceoncologie.Data.Models.Paiement", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DatePaiement")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("MethodePaiement")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<double>("Montant")
                        .HasColumnType("double");

                    b.Property<int>("PatientId")
                        .HasColumnType("int");

                    b.Property<int>("RdvId")
                        .HasColumnType("int");

                    b.Property<string>("Statut")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("PatientId");

                    b.HasIndex("RdvId")
                        .IsUnique();

                    b.ToTable("Paiements");
                });

            modelBuilder.Entity("serviceoncologie.Data.Models.Patient", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Adresse")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Categorie")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("DateNaissance")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("NCIN")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("varchar(8)");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("NumeroTelephone")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("varchar(8)");

                    b.Property<double>("Poids")
                        .HasColumnType("double");

                    b.Property<string>("Prenom")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("SituationSocial")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("SousCategorie")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<double>("Taille")
                        .HasColumnType("double");

                    b.HasKey("Id");

                    b.ToTable("Patients");
                });

            modelBuilder.Entity("serviceoncologie.Data.Models.PrestationMedicale", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Libelle")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Quantite")
                        .HasColumnType("int");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Unite")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("PrestationsMedicales");
                });

            modelBuilder.Entity("serviceoncologie.Data.Models.Protocole", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DecisionStafId")
                        .HasColumnType("int");

                    b.Property<int>("DureeProtocole")
                        .HasColumnType("int");

                    b.Property<string>("NomProtocole")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<int>("NombreCure")
                        .HasColumnType("int");

                    b.Property<string>("Rythme")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.Property<string>("TypeProtocole")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("DecisionStafId");

                    b.ToTable("Protocoles");
                });

            modelBuilder.Entity("serviceoncologie.Data.Models.Rdv", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DateRdv")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("DemandeRdvId")
                        .HasColumnType("int");

                    b.Property<int?>("DemandeRdvId1")
                        .HasColumnType("int");

                    b.Property<string>("Etat")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("MedecinId")
                        .HasColumnType("int");

                    b.Property<string>("Observation")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("PatientId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DemandeRdvId")
                        .IsUnique();

                    b.HasIndex("DemandeRdvId1")
                        .IsUnique();

                    b.HasIndex("MedecinId");

                    b.HasIndex("PatientId");

                    b.ToTable("Rdvs");
                });

            modelBuilder.Entity("serviceoncologie.Data.Models.Tache", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Libelle")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Taches");
                });

            modelBuilder.Entity("serviceoncologie.Data.Models.TacheUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("DateAdded")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("TacheId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TacheId");

                    b.HasIndex("UserId");

                    b.ToTable("TacheUsers");
                });

            modelBuilder.Entity("serviceoncologie.Data.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Adresse")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("DateDeNaissance")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("NCIN")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("varchar(8)");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<byte[]>("PhotoProfil")
                        .HasColumnType("longblob");

                    b.Property<string>("Prenom")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Sexe")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("SituationSocial")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Telephone")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Admission", b =>
                {
                    b.HasOne("serviceoncologie.Data.Models.Consultation", "Consultation")
                        .WithMany("Admissions")
                        .HasForeignKey("ConsultationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("serviceoncologie.Data.Models.DecisionStaf", "DecisionStaf")
                        .WithMany("Admissions")
                        .HasForeignKey("DecisionStafId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Consultation");

                    b.Navigation("DecisionStaf");
                });

            modelBuilder.Entity("StafMedecin", b =>
                {
                    b.HasOne("serviceoncologie.Data.Models.CommissionStaf", "CommissionStaf")
                        .WithMany("StafMedecins")
                        .HasForeignKey("commissionstafid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("serviceoncologie.Data.Models.User", "User")
                        .WithMany("StafMedecins")
                        .HasForeignKey("userid")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_StafMedecin_User_Medecin");

                    b.Navigation("CommissionStaf");

                    b.Navigation("User");
                });

            modelBuilder.Entity("serviceoncologie.Data.Models.Consultation", b =>
                {
                    b.HasOne("serviceoncologie.Data.Models.Dossier", "Dossier")
                        .WithMany("Consultations")
                        .HasForeignKey("DossierId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("serviceoncologie.Data.Models.User", "Medecin")
                        .WithMany()
                        .HasForeignKey("MedecinId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("serviceoncologie.Data.Models.Patient", "Patient")
                        .WithMany()
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Dossier");

                    b.Navigation("Medecin");

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("serviceoncologie.Data.Models.ConsultationMaladie", b =>
                {
                    b.HasOne("serviceoncologie.Data.Models.Consultation", "Consultation")
                        .WithMany("ConsultationMaladies")
                        .HasForeignKey("ConsultationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("serviceoncologie.Data.Models.Dossier", "Dossier")
                        .WithMany("ConsultationMaladies")
                        .HasForeignKey("DossierId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("serviceoncologie.Data.Models.Maladie", "Maladie")
                        .WithMany("ConsultationMaladies")
                        .HasForeignKey("MaladieId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Consultation");

                    b.Navigation("Dossier");

                    b.Navigation("Maladie");
                });

            modelBuilder.Entity("serviceoncologie.Data.Models.ConsultationPrestation", b =>
                {
                    b.HasOne("serviceoncologie.Data.Models.Consultation", "Consultation")
                        .WithMany("ConsultationPrestations")
                        .HasForeignKey("ConsultationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("serviceoncologie.Data.Models.PrestationMedicale", "PrestationMedicale")
                        .WithMany("ConsultationPrestations")
                        .HasForeignKey("PrestationMedicaleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Consultation");

                    b.Navigation("PrestationMedicale");
                });

            modelBuilder.Entity("serviceoncologie.Data.Models.Cure", b =>
                {
                    b.HasOne("serviceoncologie.Data.Models.Medicament", "Medicament")
                        .WithMany("Cures")
                        .HasForeignKey("MedicamentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("serviceoncologie.Data.Models.Protocole", "Protocole")
                        .WithMany("Cures")
                        .HasForeignKey("ProtocoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Medicament");

                    b.Navigation("Protocole");
                });

            modelBuilder.Entity("serviceoncologie.Data.Models.DciMedicament", b =>
                {
                    b.HasOne("serviceoncologie.Data.Models.Dci", "Dci")
                        .WithMany("DciMedicaments")
                        .HasForeignKey("DciId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("serviceoncologie.Data.Models.Medicament", "Medicament")
                        .WithMany("DciMedicaments")
                        .HasForeignKey("MedicamentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Dci");

                    b.Navigation("Medicament");
                });

            modelBuilder.Entity("serviceoncologie.Data.Models.DecisionStaf", b =>
                {
                    b.HasOne("serviceoncologie.Data.Models.CommissionStaf", "CommissionStaf")
                        .WithMany("DecisionStafs")
                        .HasForeignKey("CommissionStafId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("serviceoncologie.Data.Models.Consultation", "Consultation")
                        .WithMany("DecisionStafs")
                        .HasForeignKey("ConsultationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("serviceoncologie.Data.Models.Dossier", "Dossier")
                        .WithMany("DecisionStafs")
                        .HasForeignKey("DossierId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CommissionStaf");

                    b.Navigation("Consultation");

                    b.Navigation("Dossier");
                });

            modelBuilder.Entity("serviceoncologie.Data.Models.DemandeRdv", b =>
                {
                    b.HasOne("serviceoncologie.Data.Models.Patient", "Patient")
                        .WithMany("DemandesRdv")
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("serviceoncologie.Data.Models.Maladie", b =>
                {
                    b.HasOne("serviceoncologie.Data.Models.Consultation", null)
                        .WithMany("Maladies")
                        .HasForeignKey("ConsultationId");

                    b.HasOne("serviceoncologie.Data.Models.User", "Medecin")
                        .WithMany("MaladiesCodées")
                        .HasForeignKey("MedecinId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Medecin");
                });

            modelBuilder.Entity("serviceoncologie.Data.Models.Paiement", b =>
                {
                    b.HasOne("serviceoncologie.Data.Models.Patient", "Patient")
                        .WithMany("Paiements")
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("serviceoncologie.Data.Models.Rdv", "Rdv")
                        .WithOne("Paiement")
                        .HasForeignKey("serviceoncologie.Data.Models.Paiement", "RdvId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Patient");

                    b.Navigation("Rdv");
                });

            modelBuilder.Entity("serviceoncologie.Data.Models.Protocole", b =>
                {
                    b.HasOne("serviceoncologie.Data.Models.DecisionStaf", "DecisionStaf")
                        .WithMany("Protocoles")
                        .HasForeignKey("DecisionStafId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DecisionStaf");
                });

            modelBuilder.Entity("serviceoncologie.Data.Models.Rdv", b =>
                {
                    b.HasOne("serviceoncologie.Data.Models.DemandeRdv", "DemandeRdv")
                        .WithOne()
                        .HasForeignKey("serviceoncologie.Data.Models.Rdv", "DemandeRdvId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("serviceoncologie.Data.Models.DemandeRdv", null)
                        .WithOne("Rdv")
                        .HasForeignKey("serviceoncologie.Data.Models.Rdv", "DemandeRdvId1");

                    b.HasOne("serviceoncologie.Data.Models.User", "Medecin")
                        .WithMany()
                        .HasForeignKey("MedecinId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("serviceoncologie.Data.Models.Patient", "Patient")
                        .WithMany("Rdvs")
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DemandeRdv");

                    b.Navigation("Medecin");

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("serviceoncologie.Data.Models.TacheUser", b =>
                {
                    b.HasOne("serviceoncologie.Data.Models.Tache", "Tache")
                        .WithMany("TacheUsers")
                        .HasForeignKey("TacheId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("serviceoncologie.Data.Models.User", "User")
                        .WithMany("TacheUsers")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tache");

                    b.Navigation("User");
                });

            modelBuilder.Entity("serviceoncologie.Data.Models.CommissionStaf", b =>
                {
                    b.Navigation("DecisionStafs");

                    b.Navigation("StafMedecins");
                });

            modelBuilder.Entity("serviceoncologie.Data.Models.Consultation", b =>
                {
                    b.Navigation("Admissions");

                    b.Navigation("ConsultationMaladies");

                    b.Navigation("ConsultationPrestations");

                    b.Navigation("DecisionStafs");

                    b.Navigation("Maladies");
                });

            modelBuilder.Entity("serviceoncologie.Data.Models.Dci", b =>
                {
                    b.Navigation("DciMedicaments");
                });

            modelBuilder.Entity("serviceoncologie.Data.Models.DecisionStaf", b =>
                {
                    b.Navigation("Admissions");

                    b.Navigation("Protocoles");
                });

            modelBuilder.Entity("serviceoncologie.Data.Models.DemandeRdv", b =>
                {
                    b.Navigation("Rdv");
                });

            modelBuilder.Entity("serviceoncologie.Data.Models.Dossier", b =>
                {
                    b.Navigation("ConsultationMaladies");

                    b.Navigation("Consultations");

                    b.Navigation("DecisionStafs");
                });

            modelBuilder.Entity("serviceoncologie.Data.Models.Maladie", b =>
                {
                    b.Navigation("ConsultationMaladies");
                });

            modelBuilder.Entity("serviceoncologie.Data.Models.Medicament", b =>
                {
                    b.Navigation("Cures");

                    b.Navigation("DciMedicaments");
                });

            modelBuilder.Entity("serviceoncologie.Data.Models.Patient", b =>
                {
                    b.Navigation("DemandesRdv");

                    b.Navigation("Paiements");

                    b.Navigation("Rdvs");
                });

            modelBuilder.Entity("serviceoncologie.Data.Models.PrestationMedicale", b =>
                {
                    b.Navigation("ConsultationPrestations");
                });

            modelBuilder.Entity("serviceoncologie.Data.Models.Protocole", b =>
                {
                    b.Navigation("Cures");
                });

            modelBuilder.Entity("serviceoncologie.Data.Models.Rdv", b =>
                {
                    b.Navigation("Paiement");
                });

            modelBuilder.Entity("serviceoncologie.Data.Models.Tache", b =>
                {
                    b.Navigation("TacheUsers");
                });

            modelBuilder.Entity("serviceoncologie.Data.Models.User", b =>
                {
                    b.Navigation("MaladiesCodées");

                    b.Navigation("StafMedecins");

                    b.Navigation("TacheUsers");
                });
#pragma warning restore 612, 618
        }
    }
}
